= labelbuddy
Jérôme Dockès <jerome@dockes.org>
:homepage: https://jeromedockes.github.io/labelbuddy
:lang: en
:idprefix:
:idseparator: -
:ghrepo: https://github.com/jeromedockes/labelbuddy/
:lblicense: https://github.com/jeromedockes/labelbuddy/blob/main/LICENSE.txt
:polinelab-home: https://neurodatascience.github.io/
:lb: pass:q[*labelbuddy*]
:downloads-link: link:https://jeromedockes.github.io/labelbuddy/labelbuddy/current/installation

image::labelbuddy-animated.svg[256,256,align="left"]

[.animated-highlight.animated-highlight-yellow.animation-delay-1s]#{lb}# is a desktop application for text labelling: [.animated-highlight.animated-highlight-blue.animation-delay-3s]#tagging spans of text# with different labels.
Manual text annotations are useful for information extraction, a variety of Natural Language Processing tasks, literature reviews, and in many other contexts.

{lb} is a lightweight application, [.animated-highlight.animated-highlight-yellow.animation-delay-5s]#easy to install and use#.
To get started, {downloads-link}[download] {lb}, and have a look at the xref:documentation.adoc[documentation].
You can also see some xref:screenshots.adoc[screenshots].

{lb} is {lblicense}[open-source], and the source code is hosted on {ghrepo}[GitHub].

{lb} was created to support text-mining and meta-analysis research projects in the {polinelab-home}[ORIGAMI lab] at McGill University.
It should be suitable for a wide variety of text annotation projects.

.Some features of {lb}
****
- *Open source.* It is completely free and always will be.
- *Easy to install* on Linux, Windows or MacOS.
You can also download and run {lb} *without installing* it.
No accounts, configuration, or containers -- start labelling right away!
- *Sequence labelling* with predefined labels or free-form annotations.
A simple interface and keyboard shortcuts help annotate documents quickly.
- *Simple file formats* to import your data from.
Choose between JSON, JSONLines or plain text.
Export your annotations to these same formats.
- *Native application* -- not a web application running on a server.
An annotation database is a single ordinary file.
Data can be imported and exported with a command-line interface.
****
