= Installing labelbuddy
Jérôme Dockès <jerome@dockes.org>
:experimental:
:homepage: https://jeromedockes.github.io/labelbuddy/
:lang: en
ifndef::site-gen-antora[]
:webfonts!:
:toc: left
:prewrap!:
:source-highlighter: pygments
endif::[]
:idprefix:
:idseparator: -
:lbppa: https://launchpad.net/~jdockes/+archive/ubuntu/labelbuddy
:lbppapackages: https://launchpad.net/~jdockes/+archive/ubuntu/labelbuddy/+packages
:ghreleases: https://github.com/jeromedockes/labelbuddy/releases
:ghrepo: https://github.com/jeromedockes/labelbuddy/
:lb: pass:q[*labelbuddy*]
:doca: pass:q[*doccano*]
:ietab: pass:q["`Import / Export`" tab]
:annotab: pass:q["`Annotate`" tab]
:dstab: pass:q["`Dataset`" tab]


ifndef::site-gen-antora[]
This document describes how to install <<index#,{lb}>>.
endif::[]


== Installing a binary copy


=== On Ubuntu

Packages built for different Ubuntu distributions are published on {lbppa}[this Personal Package Archive].
Add it to your system by executing:
....
sudo add-apt-repository -y ppa:jdockes/labelbuddy
sudo apt-get update
....

Then the latest release of {lb} (and any future releases) can be installed with:
....
sudo apt-get install labelbuddy
....

If you don't want to add the PPA to your sources list you can manually choose and download one of the {lbppapackages}[published packages], then install it with `apt`:

....
sudo apt install ./labelbuddy_<version>.deb
....

=== On Debian

Binary packages can be downloaded from {ghreleases}[the releases page on GitHub].
Once you have downloaded the package, you can install it with `apt`:
....
sudo apt install ./labelbuddy_<version>.deb
....

=== On Windows

Select the latest release from {ghreleases}[here], and download and run `labelbuddy_<version>_windows_installer.exe` (ignore Windows’ security warnings).
{lb} can be uninstalled from the Windows applications menu, or by running the `maintenancetool.exe` executable found in the {lb} installation folder.

An alternative to using the installer is to download `labelbuddy_windows.zip`, unzip it anywhere, then execute the file `labelbuddy.exe` that it contains to start {lb}.

=== On MacOS

Select the latest release from {ghreleases}[here], and download `labelbuddy_<version>.dmg`.
Double-click the downloaded file, and from the window that opens drag `labelbuddy` into the `/Applications` folder in *Finder*.

== Building from source

Download a source distribution from {ghreleases}[GitHub], the {lb} {lbppapackages}[PPA], or get the latest code by cloning or downloading the {lb} {ghrepo}[git repository].

{lb} uses https://www.qt.io/[Qt 5]. Qt can probably be installed with your package manager, for example:
....
apt-get install qt5-default
....
or
....
yum install qt5-qtbase
yum install qt5-qtbase-devel
....

Otherwise you can get it from the https://www.qt.io/download-qt-installer[Qt downloads page].

{lb} can be built with https://cmake.org/[CMake]. In an empty directory run:
....
cmake /path/to/labelbuddy
cmake --build .
....

Then {lb} can (optionally) be installed with:
....
sudo make install
....

{lb} can also be built with https://doc.qt.io/qt-5/qmake-manual.html[qmake]:
....
qmake /path/to/labelbuddy
make
....

Building {lb} should be straightforward, so if you run into any difficulties please open a https://github.com/jeromedockes/labelbuddy/issues[GitHub issue].
