= Installing labelbuddy
Jérôme Dockès <jerome@dockes.org>
:experimental:
:homepage: https://jeromedockes.github.io/labelbuddy/
:lang: en
:webfonts!:
:toc: left
:idprefix:
:idseparator: -
:prewrap!:
:source-highlighter: pygments
:lbppa: https://launchpad.net/~jdockes/+archive/ubuntu/labelbuddy
:lbppapackages: https://launchpad.net/~jdockes/+archive/ubuntu/labelbuddy/+packages
:ghreleases: https://github.com/jeromedockes/labelbuddy/releases
:ghrepo: https://github.com/jeromedockes/labelbuddy/
:lb: pass:q[*labelbuddy*]
:doca: pass:q[*doccano*]
:ietab: pass:q["`Import / Export`" tab]
:annotab: pass:q["`Annotate`" tab]
:dstab: pass:q["`Dataset`" tab]


This document describes how to install <<index#,{lb}>>.


== Installing a binary copy


=== On Ubuntu

Packages built for different Ubuntu distributions are published on {lbppa}[this Personal Package Archive].
Add it to your system by executing:
....
sudo add-apt-repository ppa:jdockes/labelbuddy
sudo apt-get update
....

Then the latest release of {lb} (and any future releases) can be installed with:
....
sudo apt-get install labelbuddy
....

If you don't want to add the PPA to your sources list you can manually choose and download one of the {lbppapackages}[published packages], then install it with `apt-get`.
For example:

....
sudo apt install ./labelbuddy_0.0.1-1~groovy1_amd64.deb
....

=== On Windows

Select the latest release from {ghreleases}[the releases page on GitHub], and download and run `labelbuddy_windows_installer.exe` (ignore Windows’ security warnings).
An alternative to the installer is to download `labelbuddy_windows.zip`, unzip it anywhere, then execute the file `labelbuddy.exe` that it contains to start {lb}.


== Building from source

Download a source distribution from {ghreleases}[GitHub], the {lb} {lbppapackages}[PPA], or get the latest code by cloning or downloading the {lb} {ghrepo}[git repository].

{lb} uses https://www.qt.io/[Qt 5]. Qt can probably be installed with your package manager, for example:
....
apt-get install qt5-default
....

Otherwise you can get it from the https://www.qt.io/download-qt-installer[Qt downloads page].

{lb} can be built with https://cmake.org/[CMake]. In an empty directory run:
....
cmake /path/to/labelbuddy
cmake --build .
....

It can also be built with https://doc.qt.io/qt-5/qmake-manual.html[qmake]:
....
qmake /path/to/labelbuddy
make
....

Building {lb} should be straightforward, so if you run into any difficulties please open a https://github.com/jeromedockes/labelbuddy/issues[GitHub issue].
