name: Build labelbuddy for MacOS

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build_macos:
    runs-on: macos-11
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          setup-python: 'false'

      - name: Build dmg
        working-directory: ${{ runner.temp }}
        run: |
          ${{ github.workspace }}/scripts/build_dmg.sh

      - name: Upload dmg
        uses: actions/upload-artifact@v3
        with:
          name: dmg
          path: ${{ runner.temp }}/labelbuddy-*.dmg*
