name: Build AppImage

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build_appimage:
    runs-on: ubuntu-latest
    container: debian:stretch
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt & utils
        run: |
          apt-get update
          apt-get install -y cmake
          apt-get install -y qt5-default
          apt-get install -y build-essential
          apt-get install -y wget
          apt-get install -y fuse
          apt-get install -y file

      - name: Build AppImage
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
        run: |
          scripts/build_appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: ./*.AppImage

      - name: Upload AppDir
        uses: actions/upload-artifact@v3
        with:
          name: AppDir
          path: ./AppDir
