name: Build labelbuddy for MacOS

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build_macos:
    runs-on: macos-11
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Install dependencies
        run: brew install unixodbc

      - name: Build dmg
        working-directory: ${{ runner.temp }}
        run: |
          qmake ${{ github.workspace }}/labelbuddy.pro "CONFIG += app_bundle" -config release
          make
          macdeployqt labelbuddy.app -dmg

      - name: Upload dmg
        uses: actions/upload-artifact@v3
        with:
          name: dmg
          path: ${{ runner.temp }}/labelbuddy.dmg
