name: Build AppImage

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build_appimage:
    runs-on: ubuntu-latest
    container: debian:stretch
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        run: |
          apt-get update
          apt-get install -y cmake
          apt-get install -y qt5-default
          apt-get install -y build-essential

      - name: Build AppImage
        run: |
          scripts/build_appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: ./*.AppImage
